name: Perform pre-commit checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
    # Initialization
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
      with:
        python-version: 3.12

    # Cache
    - name: Load pre-commit hooks cache
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{ hashFiles('tests/.pre-commit-config.yaml') }}

    # Basic install
    - name: Install pre-commit
      run: python -m pip install pre-commit
    - name: List pip package versions
      run: python -m pip freeze --local

    # Run pre-commit
    - name: RUN PRE-COMMIT
      run: |
        set -xe
        cp tests/.pre-commit-config.yaml .
        SKIP=no-commit-to-branch pre-commit run --show-diff-on-failure --color=always --all-files

    # Upload logs
    - name: Upload pre-commit log
      if: always()
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: pre-commit-log
        path: /home/runner/.cache/pre-commit/pre-commit.log
